CREATE DATABASE company;
CREATE TABLE Employee(
SSN CHAR(9) PRIMARY KEY,
FName VARCHAR(20),
LName VARCHAR(20), 
Gender CHAR(1), 
BD DATE,
SuperSSN CHAR(9) NULL, 
DNo INT,
FOREIGN KEY (SuperSSN) REFERENCES Employee (SSN),
FOREIGN KEY (DNo) REFERENCES Department,
);

CREATE TABLE Department(
DNo INT PRIMARY KEY, 
DName VARCHAR(30), 
ManagerId CHAR(9), 
HireDate DATE,
FOREIGN KEY (ManagerId) REFERENCES Employee(SSN)
);

CREATE TABLE Locations(
DNo INT,
Location VARCHAR(30),
PRIMARY KEY(DNo, location),
FOREIGN KEY (DNo) REFERENCES Department(DNo)
);

CREATE TABLE Dependent(
SSN CHAR(9),
DName VARCHAR(20),
GENDER CHAR(1),
BD DATE,
PRIMARY KEY(SSN, DName),
FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
);

CREATE TABLE Project(
PNo INT PRIMARY KEY,
PName VARCHAR(30),
City VARCHAR(30),
Location VARCHAR(30),
DNo INT, 
FOREIGN KEY(DNo) REFERENCES Department(DNo)
);

CREATE TABLE ProjectWork(
SSN CHAR(9),
PNo INT,
PRIMARY KEY (SSN, PNo),
FOREIGN KEY(SSN) REFERENCES EMPLOYEE(SSN),
FOREIGN KEY (PNo) REFERENCES Project(PNo)
);







